
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 13;
  public static final int IDENT = 7;
  public static final int PTVIRG = 3;
  public static final int FP = 12;
  public static final int AC = 9;
  public static final int EOF = 0;
  public static final int MAT = 6;
  public static final int VAR = 2;
  public static final int IF = 8;
  public static final int ELSE = 14;
  public static final int CON = 4;
  public static final int error = 1;
  public static final int FC = 10;
  public static final int AT = 5;
  public static final int AP = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "PTVIRG",
  "CON",
  "AT",
  "MAT",
  "IDENT",
  "IF",
  "AC",
  "FC",
  "AP",
  "FP",
  "WHILE",
  "ELSE"
  };
}

